version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: notpassword
    volumes: 
      - MySQL-data:/var/lib/mysql
    ports:
      - 3306:3306


volumes:
  MySQL-data: